### ISSUE TITLE
spring-cloud-commons usage of bcprov-jdk18on 1.81 with CVE's

### ISSUE THREAD

**Issue by wleese** [bcgit/bc-java#2293]
I opened [this issue with spring-cloud-commons](https://github.com/spring-cloud/spring-cloud-commons/issues/1688), but was surprised they couldn't upgrade due to I assume backwards incompatibility.

Would it be possible to release a patch release with fixes for e.g. https://github.com/advisories/GHSA-c3fc-8qff-9hwx ?

**Comment by ryanjbaxter** [comment]
> I opened https://github.com/spring-cloud/spring-cloud-commons/issues/1688, but was surprised they couldn't upgrade due to I assume backwards incompatibility.

Yes the concern is any kind of breaking changes in a minor we release.  If we release a minor with a dependency users are using with breaking changes than that impacts their ability to upgrade to our minor release.

**Comment by dghgit** [comment]
The commit for this is listed in the BC wiki page. Ah, I see, just read the Spring page. If I understand correctly what you're asking for is a patch release containing only CVE fixes for 1.81? If we do that they'll be able to update immediately (assuming the CVE fixes in themselves don't cause anything to break).

**Comment by ryanjbaxter** [comment]
@dghgit that is correct.  Actually we have a branch using 1.80 as well so a patch release for 1.80 and 1.81 would be great!

**Comment by roy-basmacier** [comment]
@ryanjbaxter @wleese 
1.81.1 is now available at https://downloads.bouncycastle.org/betas/.  Backports the 5 CVE fixes from 1.84 to the 1.81 branch. 

~ Roy

**Comment by dghgit** [comment]
If 1.81.1 works out okay, we'll look at doing a 1.80 one as well.

**Comment by ryanjbaxter** [comment]
@roy-basmacier thanks, when will that be available on maven central?

**Comment by dghgit** [comment]
@ryanjbaxter I can publish to Maven Central as soon as you can confirm it does the job and there's no issues with the artefacts. Realise this may sound a bit overly cautious, but on Maven Central everything's immutable. We get one shot per version and that's it!

**Comment by roy-basmacier** [comment]
@ryanjbaxter 1.80.2 is up https://downloads.bouncycastle.org/betas/

**Comment by dghgit** [comment]
@ryanjbaxter just a reminder we are waiting on your go ahead for Maven Central publication. For avoidance of confusion, artifacts that will be published to maven are contained in the following jars with the SHA-256 checksums below.

22820d1e2fbff0b4829614fb936e91cbadefb9025b2746ee14b5c2e3ba7fa5ae  bc-jdk18on-1.80.2.tgz
b7293885b32261d75e4c370fcade66f98f634ca3ec539c12c8aad45e36490351  bc-jdk18on-1.81.1.tgz

**Comment by ryanjbaxter** [comment]
@dghgit thanks for your patience.  I ran our build against both releases and didn't see any issues on my end.

**Comment by ryanjbaxter** [comment]
@dghgit I was just building another project and I ran into this error, could it be related?

```
[ERROR] org.springframework.cloud.kubernetes.k8s.client.catalog.watcher.KubernetesClientCatalogWatchEndpointsIT -- Time elapsed: 0.017 s <<< ERROR!
java.lang.NoClassDefFoundError: org/bouncycastle/util/io/pem/PemObjectGenerator
        at io.kubernetes.client.util.credentials.ClientCertificateAuthentication.provide(ClientCertificateAuthentication.java:43)
        at io.kubernetes.client.util.credentials.KubeconfigAuthentication.provide(KubeconfigAuthentication.java:90)
        at io.kubernetes.client.util.ClientBuilder.build(ClientBuilder.java:470)
        at io.kubernetes.client.util.Config.fromConfig(Config.java:98)
        at io.kubernetes.client.util.Config.fromConfig(Config.java:94)
        at org.springframework.cloud.kubernetes.integration.tests.commons.native_client.NativeClientKubernetesFixture.<init>(NativeClientKubernetesFixture.java:85)
        at org.springframework.cloud.kubernetes.integration.tests.commons.k3s.NativeClientIntegrationTestExtension.lambda$nativeClientKubernetesFixture$0(NativeClientIntegrationTestExtension.java:215)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.springframework.cloud.kubernetes.integration.tests.commons.k3s.NativeClientIntegrationTestExtension.nativeClientKubernetesFixture(NativeClientIntegrationTestExtension.java:214)
        at org.springframework.cloud.kubernetes.integration.tests.commons.k3s.NativeClientIntegrationTestExtension.beforeAll(NativeClientIntegrationTestExtension.java:54)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        Suppressed: java.lang.NoClassDefFoundError: org/bouncycastle/util/io/pem/PemObjectGenerator
                at io.kubernetes.client.util.credentials.ClientCertificateAuthentication.provide(ClientCertificateAuthentication.java:43)
                at io.kubernetes.client.util.credentials.KubeconfigAuthentication.provide(KubeconfigAuthentication.java:90)
                at io.kubernetes.client.util.ClientBuilder.build(ClientBuilder.java:470)
                at io.kubernetes.client.util.Config.fromConfig(Config.java:98)
                at io.kubernetes.client.util.Config.fromConfig(Config.java:94)
                at org.springframework.cloud.kubernetes.integration.tests.commons.native_client.NativeClientKubernetesFixture.<init>(NativeClientKubernetesFixture.java:85)
                at org.springframework.cloud.kubernetes.integration.tests.commons.k3s.NativeClientIntegrationTestExtension.lambda$nativeClientKubernetesFixture$0(NativeClientIntegrationTestExtension.java:215)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.springframework.cloud.kubernetes.integration.tests.commons.k3s.NativeClientIntegrationTestExtension.nativeClientKubernetesFixture(NativeClientIntegrationTestExtension.java:214)
                at org.springframework.cloud.kubernetes.integration.tests.commons.k3s.NativeClientIntegrationTestExtension.afterAll(NativeClientIntegrationTestExtension.java:133)
                ... 1 more
        Caused by: java.lang.ClassNotFoundException: org.bouncycastle.util.io.pem.PemObjectGenerator
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
                at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
                ... 11 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.util.io.pem.PemObjectGenerator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 11 more

```

**Comment by dghgit** [comment]
PemObjectGenerator is in both bcprov and bccore. In your case you probably only want to include bcprov - if you're seeing an error like this it usually means the BC classes have been included on the path twice, so there may also be an old version of BC somewhere.

**Comment by ryanjbaxter** [comment]
That probably makes sense as I just dropped the jars in my local maven repo without cleaning it out

**Comment by dghgit** [comment]
Okay, I'll organise publishing to Maven Central today. Will let you know.

**Comment by dghgit** [comment]
Patch releases 1.80.2 and 1.81.1 should now both be on Maven Central.

**Comment by breun** [comment]
@dghgit I see version 1.80.2 of `org.bouncycastle:bc-jdk18on-bom` on https://central.sonatype.com/artifact/org.bouncycastle/bc-jdk18on-bom/versions, but no version 1.81.1. Will there be a 1.81.1 release of the BOM as well?

**Comment by dghgit** [comment]
I expect you'll see it in about 20 minutes! Sorry, for some reason it validated a bit after the others so got missed in the publishing pass.

**Comment by breun** [comment]
@dghgit Thanks, I see `org.bouncycastle:bc-jdk18on-bom:1.81.1` is there now too. 👍

**Comment by ryanjbaxter** [comment]
The upgrades have been merged into spring cloud thanks!

**Comment by ryanjbaxter** [comment]
Ugh I just saw this failure when upgrading from 1.80 to 1.80.2
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.747 s <<< FAILURE! -- in org.springframework.cloud.config.client.tls.ConfigClientConfigDataTlsTests
Error:  org.springframework.cloud.config.client.tls.ConfigClientConfigDataTlsTests -- Time elapsed: 0.747 s <<< ERROR!
java.lang.NoSuchFieldError: id_ml_dsa_44
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<clinit>(Unknown Source)
	at org.springframework.cloud.config.client.tls.KeyTool.signCert(KeyTool.java:96)
	at org.springframework.cloud.config.client.tls.KeyTool.createCert(KeyTool.java:68)
	at org.springframework.cloud.config.client.tls.KeyTool.createCA(KeyTool.java:38)
	at org.springframework.cloud.config.client.tls.AbstractTlsSetup.createCertificates(AbstractTlsSetup.java:37)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] Running org.springframework.cloud.config.client.tls.ConfigClientTlsTests
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.357 s <<< FAILURE! -- in org.springframework.cloud.config.client.tls.ConfigClientTlsTests
Error:  org.springframework.cloud.config.client.tls.ConfigClientTlsTests -- Time elapsed: 0.357 s <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.operator.jcajce.JcaContentSignerBuilder
	at org.springframework.cloud.config.client.tls.KeyTool.signCert(KeyTool.java:96)
	at org.springframework.cloud.config.client.tls.KeyTool.createCert(KeyTool.java:68)
	at org.springframework.cloud.config.client.tls.KeyTool.createCA(KeyTool.java:38)
	at org.springframework.cloud.config.client.tls.AbstractTlsSetup.createCertificates(AbstractTlsSetup.java:37)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: id_ml_dsa_44 [in thread "main"]
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<clinit>(Unknown Source)
	... 6 more

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    ConfigClientConfigDataTlsTests>AbstractTlsSetup.createCertificates:37 » NoSuchField id_ml_dsa_44
Error:    ConfigClientTlsTests>AbstractTlsSetup.createCertificates:37 » NoClassDefFound Could not initialize class org.bouncycastle.operator.jcajce.JcaContentSignerBuilder
```

**Comment by ryanjbaxter** [comment]
NVM sorry for the noise, it was a classpath issue

**Comment by dghgit** [comment]
I was just about to post that. So it's all working and we can close this one off?

**Comment by ryanjbaxter** [comment]
So far it looks good.  You can close it for now and I will let you know if I see any issues

**Comment by dghgit** [comment]
Thanks. Closing, fingers crossed!

**Comment by breun** [comment]
@dghgit Do you know if the security advisory will be updated to indicate that 1.80.2 and 1.81.1 fix this issue, so security scanners will no longer flag those versions as vulnerable to this CVE?

**Comment by dghgit** [comment]
The NVD has now been updated properly. 

See:
https://www.cve.org/cverecord?id=CVE-2025-14813
https://www.cve.org/cverecord?id=CVE-2026-0636
https://www.cve.org/cverecord?id=CVE-2026-3505
https://www.cve.org/cverecord?id=CVE-2026-5588
https://www.cve.org/cverecord?id=CVE-2026-5598

I should mention it may take a couple of days for everything down stream to update though... but it you direct any enquiries to the www.cve.org above, it should provide an adequate answer.

**Comment by Nephery** [comment]
@dghgit I think there's a typo in the update for https://www.cve.org/cverecord?id=CVE-2026-5598 . 

The `Product Status` says:

```
affected from 1.81 before 1.80.1
```

Instead of saying `before 1.81.1` like the other CVEs:

```
affected from 1.81 before 1.81.1
```
