### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bouncycastle.jce.provider.BouncyCastleProvider"

### ISSUE THREAD

**Issue by SharathK-Android** [bcgit/bc-java#1726]
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bouncycastle.jce.provider.BouncyCastleProvider" on path: DexPathList[***] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)                                                                                       

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/bouncycastle/crypto/digests/SHA1Digest;
    at features.home.presentation.MainActivity.initUserInterface(MainActivity.kt:185) Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bouncycastle.crypto.digests.SHA1Digest" on path: DexPathList[***] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    
After updating the JDK version to 17 and the Gradle plugin to 8.5, my android application is crashing while creating an instance SHA1Digest and BouncyCastleProvider class with the above mentioned exception during runtime.

I am using below dependency

dependencies {
     implementation "org.bouncycastle:bcprov-jdk15to18:1.78.1"
}

**Comment by sai-keerthan** [comment]
Please add the bcpkix dependency too.

**Comment by dghgit** [comment]
Inactive.
