### ISSUE TITLE
NoSuchMethodError on BigInteger.intValueExact() when loading PKCS12 keystore on Android API 29

### ISSUE THREAD

**Issue by alexisdelage** [bcgit/bc-java#2369]
### Description

After upgrading from bcprov/bcpkix/bcutil-jdk18on 1.84 → 1.85, loading a PKCS12
keystore via `KeyStore.getInstance("PKCS12", BouncyCastleProvider()).load(...)`
crashes at runtime on Android API 29 with:

```
FATAL EXCEPTION: main
java.lang.NoSuchMethodError: No virtual method intValueExact()I in class Ljava/math/BigInteger; or its super classes (declaration of 'java.math.BigInteger' appears in /apex/com.android.runtime/javalib/core-libart.jar)
	at org.bouncycastle.util.BigIntegers.intValueExact(Unknown Source:0)
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12Util.validateIterationCount(Unknown Source:30)
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source:82)
	at org.bouncycastle.jcajce.provider.keystore.util.AdaptingKeyStoreSpi.engineLoad(Unknown Source:70)
	at java.security.KeyStore.load(KeyStore.java:1484)
```

This reproduces only on the second keystore I load in my app, but not on the first keystore I load (independently of the order I load the two keystores). Both KeyStores load use the same BouncyCastleProvider instance (but not the same KeyStore instance).

### Environment

- org.bouncycastle:bcprov-jdk18on / bcutil-jdk18on / bcpkix-jdk18on: 1.85 (works fine on 1.84)
- Android device: Android 10 (API 29) physical device
- compileAndroidSdk: 36
- Kotlin 2.4.10, JVM target 17
- Java compileOptions sourceCompatibility and targetCompatibility: Java 17

### Workaround

Pinning back to 1.84 avoids the crash.

**Comment by dghgit** [comment]
You should find bcprov-jdk15to18-1.85.1 will work - it's a miracle, although not entirely surprising you haven't run into this before.  Even in 1.84 there are a few things which would trigger in API 29. That said, we can probably downgrade at least those methods so you can still use the supported "modern features".

I should probably add, you do not want to be running 1.84. See docs/releasenotes.html in this repository for details.

**Comment by roy-basmacier** [comment]
Hi @alexisdelage,
The fix is now live in the latest beta: https://downloads.bouncycastle.org/betas/
Let us know if the issue is resolved and that there aren't any other issues on the Android platform.

**Comment by alexisdelage** [comment]
Hi @dghgit and @roy-basmacier,

I finally had time to test your solutions, and both jdk15to18-1.85.1 and jdk18on-1.86 beta fix the problem!

So I will use the jdk15to18-1.85.1 for the moment, and then switch to jdk18on-1.86 when it will be released.

Thanks for your time!

**Comment by OrangeDog** [comment]
The missing method will be available in the next release of Android desugaring:

https://issuetracker.google.com/issues/540020386
