### ISSUE TITLE
Reproducing Maven builds

### ISSUE THREAD

**Issue by tinchou** [bcgit/bc-java#378]
Hi!

At my company we're planning on using BouncyCastle. We want to use the dependency you publish on Maven, but for security reasons we need to build the JAR file ourselves first and verify it matches the published one.

I'm wondering if you could give me some details about your release process so I could build the project in the same conditions. Here's what I tried, unsuccessfully:

I started with the following `Dockerfile`:

```dockerfile
FROM openjdk:8-jdk

RUN apt update
RUN apt install -y --no-install-recommends ant wget diffoscope git

RUN mkdir -p /opt/junit
RUN wget http://central.maven.org/maven2/junit/junit/4.12/junit-4.12.jar -O /opt/junit/junit.jar

RUN mkdir -p /opt/javamail
RUN wget http://central.maven.org/maven2/javax/mail/javax.mail-api/1.6.1/javax.mail-api-1.6.1.jar -O /opt/javamail/mail.jar

RUN mkdir -p /opt/jaf
RUN wget http://central.maven.org/maven2/javax/activation/activation/1.1.1/activation-1.1.1.jar -O /opt/jaf/activation.jar

WORKDIR /code
RUN git clone https://github.com/bcgit/bc-java.git
WORKDIR /code/bc-java
RUN git checkout r1rv59
RUN sh build15+
```

Building:

```sh
docker build -t bouncycastle-build .
```

And then extracting the generated JAR:

```sh
docker run --name temp-container-name bouncycastle-build /bin/true
docker cp temp-container-name:/code/bc-java/build/artifacts/jdk1.5/jars/bcprov-jdk15on-159.jar ./bcprov-jdk15on-159.jar
docker rm temp-container-name
```

When I compare this with the published jar, I just get too many differences (this will take a while... you can pass `--debug` to diffoscope to see progress):

```sh
wget http://central.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.59/bcprov-jdk15on-1.59.jar -O bcprov-jdk15on-159-maven.jar
diffoscope --html report.html bcprov-jdk15on-159.jar bcprov-jdk15on-159-maven.jar
```

The first thing that stands out is the contents of the `MANIFEST.MF` file, which is ~500kb in your release but it's almost empty in mine.

**Comment by bcgit** [comment]
The jar needs to be signed with a JCE signing certificate. That's the difference you are seeing in MANIFEST.MF. You'd also need to compile with 1.5 as the target to reproduce what we do.
I guess I should also mention that if the provider jar is not signed by a JCE certificate, it will be very limited in what it can do.

**Comment by tinchou** [comment]
My goal is to verify the `.class` binary files, not to actually use the generated JARs, so the JCE certificate isn't a problem. Since compiling with OpenJDK 1.8 yields very different files, I switched to Oracle JDK 1.5.

I downloaded `J2SE(TM) Development Kit 5.0 Update 8` (http://download.oracle.com/otn/java/jdk/1.5.0_08/jdk-1_5_0_08-linux-amd64.bin) and tried reproducing the build again, but this time I'm seeing errors about missing `javax.net` and `javax.crypto` packages like these:

```
  [javadoc] /code/bc-java/build/artifacts/jdk1.5/bcprov-jdk15on-159/src/org/bouncycastle/jce/provider/test/AEADTest.java:17: cannot find symbol
  [javadoc] symbol  : class GCMParameterSpec
  [javadoc] location: package javax.crypto.spec
  [javadoc] import javax.crypto.spec.GCMParameterSpec;
```

```
    [javac] /code/bc-java/build/artifacts/jdk1.5/bctls-jdk15on-159/src/org/bouncycastle/jsse/provider/ProvSSLContextSpi.java:18: cannot find symbol
    [javac] symbol  : class SSLParameters
    [javac] location: package javax.net.ssl
    [javac] import javax.net.ssl.SSLParameters;
    [javac]                      ^
    [javac] /code/bc-java/build/artifacts/jdk1.5/bctls-jdk15on-159/src/org/bouncycastle/jsse/provider/ProvSSLContextSpi.java:382: cannot find symbol
    [javac] symbol  : class SSLParameters
    [javac] location: class org.bouncycastle.jsse.provider.ProvSSLContextSpi
    [javac]     protected SSLParameters engineGetDefaultSSLParameters()
    [javac]               ^
    [javac] /code/bc-java/build/artifacts/jdk1.5/bctls-jdk15on-159/src/org/bouncycastle/jsse/provider/ProvSSLContextSpi.java:412: cannot find symbol
    [javac] symbol  : class SSLParameters
    [javac] location: class org.bouncycastle.jsse.provider.ProvSSLContextSpi
    [javac]     protected SSLParameters engineGetSupportedSSLParameters()
    [javac]               ^
    [javac] /code/bc-java/build/artifacts/jdk1.5/bctls-jdk15on-159/src/org/bouncycastle/jsse/provider/JsseUtils_8.java:7: cannot find symbol
    [javac] symbol  : class SNIHostName
    [javac] location: package javax.net.ssl
    [javac] import javax.net.ssl.SNIHostName;
    [javac]                      ^
    [javac] /code/bc-java/build/artifacts/jdk1.5/bctls-jdk15on-159/src/org/bouncycastle/jsse/provider/JsseUtils_8.java:8: cannot find symbol
    [javac] symbol  : class SNIServerName
    [javac] location: package javax.net.ssl
    [javac] import javax.net.ssl.SNIServerName;
    [javac]                      ^
```

I tried downloading JCE as can be seen in the following `Dockerfile` (note that it depends on having `jce-1_2_2.zip` and `jdk-1_5_0_08-linux-amd64.bin` next to it), but the errors persist:

```dockerfile
FROM ubuntu:xenial

RUN apt update
RUN apt install -y --no-install-recommends ant git unzip wget

RUN mkdir -p /opt/junit
RUN wget http://central.maven.org/maven2/junit/junit/4.12/junit-4.12.jar -O /opt/junit/junit.jar

RUN mkdir -p /opt/javamail
RUN wget http://central.maven.org/maven2/javax/mail/javax.mail-api/1.6.1/javax.mail-api-1.6.1.jar -O /opt/javamail/mail.jar

RUN mkdir -p /opt/jaf
RUN wget http://central.maven.org/maven2/javax/activation/activation/1.1.1/activation-1.1.1.jar -O /opt/jaf/activation.jar

WORKDIR /code
RUN git clone https://github.com/bcgit/bc-java.git

WORKDIR /oracle-jdk-installer
ADD jdk-1_5_0_08-linux-amd64.bin /oracle-jdk-installer
RUN echo "y\n" | sh jdk-1_5_0_08-linux-amd64.bin
ENV JDKPATH /oracle-jdk-installer/jdk1.5.0_08/

ADD jce-1_2_2.zip /oracle-jdk-installer
RUN unzip jce-1_2_2.zip jce1.2.2/lib/jce1_2_2.jar -d ./jdk1.5.0_08/jre/lib/security

WORKDIR /code/bc-java
RUN git checkout r1rv59
RUN sh build15+
```

Any pointers would be appreciated!

Thanks.

**Comment by bcgit** [comment]
1.8 should be okay, the ant script sets the target to 1.5.
